export const muskaImena = [
    "Avakum", "Avram", "Adam", "Aksentije", "Aleksa", "Aleksandar", "Alimpije", "Anđelko", "Andrija", "Antonije", "Aranđel", "Arsenije", "Atanasije", "Aćim",
    "Balša", "Bane", "Batrić", "Berislav", "Beriša", "Berko", "Blagoje", "Blagomir", "Blagota", "Blažo", "Blaško", "Bogdan", "Bogić", "Bogoboj", "Bogoljub", "Bogomir", "Bogosav", "Božidar", "Bojan", "Boran", "Borko", "Borivoj", "Borisav", "Borislav", "Boriša", "Boško", "Branimir", "Branislav", "Branko", "Bratislav", "Bratoljub", "Budimir", "Budislav",
    "Vajo", "Vasilije", "Vasilj", "Vekoslav", "Velibor", "Velizar", "Velimir", "Velisav", "Veličko", "Veljko", "Veroljub", "Veselin", "Vidak", "Vidoje", "Viktor", "Vilotije", "Vitomir", "Vićentije", "Višeslav", "Vladan", "Vladeta", "Vladimir", "Vladislav", "Vlajko", "Vlastimir", "Vojimir", "Vojin", "Vojislav", "Vujadin", "Vuk", "Vukadin", "Vukajlo", "Vukan", "Vukašin", "Vukmir", "Vukoje", "Vukosav", "Vukota", "Vuksan", "Vučko",
    "Gavra", "Gavrilo", "Gvozden", "Genadije", "Georgije", "Gerasim", "German", "Gligorije", "Gojko", "Golub", "Goran", "Gradimir", "Grgur", "Grozdan", "Gruja", "Grujica",
    "David", "Dalibor", "Damjan", "Danilo", "Darko", "Danojlo", "Desimir", "Despot", "Dimitrije", "Dimčo", "Dinko", "Dmitar", "Dobrašin", "Dobrivoj", "Dobrilo", "Dobrica", "Dobrosav", "Dojčin", "Dojčilo", "Dorotej", "Dositej", "Dragan", "Dragić", "Dragiša", "Dragoje", "Dragoljub", "Dragomir", "Dragorad", "Dragoslav", "Dragutin", "Dražo", "Draško", "Dušan",
    "Đenadije", "Đorđe", "Đukan", "Đura", "Đurađ", "Đurđe", "Đurica",
    "Emol", "Emilijan",
    "Žarko", "Želimir", "Željko", "Živadin", "Živan", "Živanko", "Živko", "Živojin", "Živomir", "Živorad", "Života", "Žika",
    "Zaviša", "Zarija", "Zarije", "Zdravko", "Zlatibor", "Zlatko", "Zlatoje", "Zlatomir", "Zlatosav", "Zoran", "Zosim", "Zrinko",
    "Ivan", "Ivica", "Ivko", "Ivo", "Ignjat", "Ignjatije", "Igor", "Ilija", "Isaija", "Isailo", "Isak", "Isidor",
    "Jagoš", "Jakov", "Jakša", "Janićije", "Janko", "Janča", "Jevrem", "Jevta", "Jevtimije", "Jezdimir", "Jelenko", "Jelisije", "Jeremija", "Jerotije", "Jovan", "Jovica", "Joviša", "Joksim", "Jordan", "Josif", "Jugomir", "Jugoslav", "Julijan", "Justin",
    "Kamenko", "Kiprijan", "Kirilo", "Kojadin", "Komnen", "Konstantin", "Kornelije", "Kosan", "Kosta", "Kostadin", "Koča", "Krsman", "Krsta", "Krstan", "Krstivoje", "Kuzman",
    "Laza", "Lazar", "Lale", "Leontije", "Lepoje", "Lepomir", "Lola", "Luka",
    "Ljuba", "Ljuban", "Ljubivoje", "Ljubinko", "Ljubiša", "Ljubo", "Ljubomir", "Ljupče",
    "Makarije", "Maksim", "Manojlo", "Marijan", "Marinko", "Marko", "Mateja", "Matija", "Melentije", "Metodije", "Mijailo", "Mijalko", "Mijat", "Miladin", "Milan", "Milanko", "Mile", "Milenko", "Milentije",
    "Mileta", "Milivoj", "Milija", "Milijan", "Milinko", "Milisav", "Milić", "Milovan", "Miloje", "Milojko", "Milorad", "Miloš", "Milun", "Milutin", "Miodrag", "Miomir", "Mirko", "Miroljub", "Miroslav", "Mirčeta", "Mitar", "Mihailo", "Mladen", "Mladomir", "Mojsilo", "Mladimir", "Momir", "Momčilo", "Moša",
    "Najdan", "Nastas", "Naum", "Nebojša", "Negovan", "Negomir", "Negoslav", "Nedeljko", "Nemanja", "Nenad", "Neofit", "Nestor", "Neško", "Nikita", "Nikodim", "Nikola", "Nikon", "Nikša", "Ninko", "Ninoslav", "Nićifor", "Novak", "Novica", "Novko",
    "Njegovan", "Njegoje", "Njegomir", "Njegosav", "Njegoslav", "Njegoš", "Njeguš",
    "Obrad", "Obradin", "Obren", "Ognjen", "Ozren", "Oliver", "Omilj", "Ostoja",
    "Pavić", "Pavle", "Pantelija", "Paun", "Peran", "Petar", "Petko", "Petronije", "Pimen", "Prvoslav", "Prvul", "Predrag", "Prerad", "Pribislav", "Prijezda", "Prodan", "Prokopije", "Prohor", "Puniša", "Puriša",
    "Radan", "Radenko", "Radivoj", "Radivoje", "Radisav", "Radič", "Radiša", "Radmilo", "Radovan", "Radoje", "Radojica", "Radojko", "Radojlo", "Radoljub", "Radoman", "Radomir", "Radonja", "Radosav", "Radoslav", "Radoš", "Radul", "Radule", "Rajica", "Rajko", "Ranđel", "Ranisav", "Ranko", "Rastivoje", "Rastislav", "Rastko", "Ratibor", "Ratimir", "Ratko", "Ratomir", "Rafailo", "Raško", "Relja", "Ristivoj", "Ristivoje", "Rozmir", "Rozomir", "Roman", "Ruvim", "Rusomir",
    "Sava", "Savatije", "Samuilo", "Svetislav", "Svetozar", "Svetoje", "Svetolik", "Sekula", "Selimir", "Serafim", "Sergije", "Sibin", "Sima", "Simeon", "Siniša", "Slaven", "Slavenko", "Slaviša", "Slavko", "Slavoljub", "Slobodan", "Sotir", "Sofronije", "Spasoje", "Spira", "Spiridon", "Spomenko", "Srba", "Srbislav", "Srboljub", "Srđa", "Srđan", "Sredoje", "Sreten", "Sretoje", "Srećko", "Srpko", "Stavra", "Stamenko", "Stanimir", "Stanislav", "Staniša", "Stanko", "Stanoje", "Stanojlo", "Steva", "Stevan", "Stepan", "Stefan", "Stojadin", "Stojan", "Stojiljko", "Stojko", "Stojmen", "Stokan", "Stole", "Strajin", "Strahinja", "Stracimir",
    "Tadija", "Tanasije", "Tanasko", "Tatomir", "Taško", "Tvrtko", "Teodor", "Teodosije", "Teofan", "Teohar", "Tešman", "Timotije", "Tiosav", "Tihomir", "Tode", "Todor", "Toma", "Tomislav", "Toplica", "Toša", "Trajan", "Trajko", "Trivun", "Trifun", "Tugomir",
    "Ćetko", "Ćile", "Ćirilo", "Ćiro",
    "Uglješa", "Ugljen", "Uranko", "Uroš",
    "Fedor", "Feodor", "Filip", "Filiman", "Filotej", "Filotije",
    "Hariton", "Hranislav", "Hristivoj", "Hristivoje",
    "Cane", "Cvetin", "Cvetko", "Cvetomir", "Cvijan", "Cvijetin", "Cvijo", "Cviko",
    "Časlav", "Čeda", "Čedomir", "Čubrilo",
    "Šako", "Šale", "Šiško", "Špiro"
  ];
  
export const zenskaImena = [
    "Agnija", "Aleksandra", "Aleksija", "Ana", "Anastasija", "Andrijana", "Anda", "Anđelija", "Anđelka", "Anica", "Anka", "Antonina",
    "Biljana", "Bisenija", "Biserka", "Blaginja", "Blagica", "Blaženka", "Bogdana", "Bogdanka", "Božana", "Božidarka", "Bojana", "Borka", "Bosiljka", "Branislava", "Branka", "Bratislava",
    "Valerija", "Varvara", "Vasilija", "Vasiljka", "Vaskrsija", "Veliborka", "Velinka", "Vera", "Verica", "Verka", "Veronika", "Veroslava", "Veselinka", "Vesna", "Vidosava", "Viktorija", "Violeta", "Višeslava", "Višnja", "Vladanka", "Vlastimirka", "Vojislava", "Vujadinka", "Vujka", "Vukosava",
    "Gavrila", "Gavrilka", "Gvozdenija", "Georgina", "Gmitra", "Gordana", "Gospava", "Grozdana",
    "Daloborka", "Damjanka", "Danica", "Danojla", "Darinka", "Desanka", "Despina", "Divna", "Dmitra", "Dobrija", "Dobrila", "Dobrinka", "Dobrica", "Doroteja", "Dostana", "Dragana", "Draginja", "Dragica", "Dragojla", "Dragoslava", "Drenka", "Drinka", "Dubravka",
    "Đenadija", "Đurđija", "Đurđevka", "Đurđica",
    "Eva", "Evgenija", "Evdokija", "Ekaterina", "Emilija",
    "Žaklina", "Želimirka", "Željka", "Živadinka", "Živana", "Živanka", "Živkica", "Živka", "Živodarka", "Živoratka", "Živoslava", "Živoslavka",
    "Zaga", "Zagorka", "Zvezdana", "Zvonka", "Zdravka", "Zlatica", "Zlatomirka", "Zora", "Zorana", "Zorica", "Zorislava", "Zorka",
    "Ivana", "Ivanka", "Ivka", "Ivona", "Ikonija", "Ilinka", "Irena", "Isidora",
    "Javorka", "Jagoda", "Jadranka", "Jana", "Janovka", "Jasmina", "Jasminka", "Jasna", "Jevdokija", "Jevrosima", "Jela", "Jelena", "Jelika", "Jelisaveta", "Jelisavka", "Jelica", "Jelka", "Jefimija", "Jovana", "Jovanka", "Jordanka", "Julija", "Julijana", "Julka",
    "Kadivka", "Kasija", "Katarina", "Katica", "Kleopatra", "Koviljka", "Kojadinka", "Kosana", "Kosara", "Kosovka", "Kostadinka", "Kristina", "Krsmanija", "Krstana", "Krstina", "Krunoslava",
    "Lara", "Latinka", "Lela", "Lena", "Lenka", "Leonida", "Leonora", "Lepa", "Leposava", "Lidija", "Liza", "Lila", "Lilijana", "Lola", "Luča", "Lučija",
    "Ljeposava", "Ljilja", "Ljiljana", "Ljuba", "Ljubica", "Ljubinka", "Ljubomirka", "Ljupka",
    "Magdalena", "Makrena", "Malina", "Margareta", "Marija", "Mašinka", "Melanija", "Miladinka", "Mileva", "Milena", "Milenija", "Melesa", "Milijana", "Miloica", "Milka", "Milojka", "Mirjana", "Miroslava", "Mitra",
    "Nada", "Nadežda", "Nastasija", "Natalija", "Nevena", "Nevenka", "Negosava", "Nedeljka", "Nerandža", "Nikolija", "Ninoslava", "Novka",
    "Njegosava", "Njegoslava",
    "Obradinka", "Obrenija", "Ozrenka", "Olga", "Olgica", "Olivera", "Oliverka", "Olja",
    "Pava", "Pavlija", "Pajka", "Paraskeva", "Pauna", "Pelagija", "Peladija", "Perka", "Persa", "Persida", "Perunika", "Petra", "Petrija", "Petruša", "Podgorka", "Poleksija", "Prvoslava", "Prvoslavka", "Prodana", "Poljka",
    "Ravija", "Ravijojla", "Radenka", "Radivojka", "Radija", "Radinka", "Radmila", "Radojka", "Radojla", "Radomirka", "Radoslava", "Radoslavka", "Razumenka", "Rajka", "Ranđija", "Ranka", "Ratiborka", "Ratka", "Roksanda", "Roksandra", "Rosanda", "Ruža", "Ružica", "Razumirka", "Rumenka",
    "Sava", "Saveta", "Savka", "Sajka", "Sandra", "Sanja", "Sara", "Svetislava", "Svetislavka", "Svetlana", "Selena", "Sibinka", "Simeuna", "Simka", "Simona", "Simonida", "Sinđelija", "Slavenka", "Slavica", "Slavka", "Slavna", "Slobodanka", "Smilja", "Smiljana", "Smiljka", "Snežana", "Soja", "Sojka", "Soka", "Sonja", "Sofija", "Spasenija", "Spomenka", "Srbijanka", "Srbislava", "Sretenka", "Stajka", "Stojka", "Staka", "Stamena", "Stamenija", "Stana", "Stanija", "Stanika", "Stanislava", "Stanica", "Stanka", "Stanojka", "Stanojla", "Stevanija", "Stevka", "Stoja", "Stojadinka", "Stojana", "Stojanka", "Stojka", "Stojna", "Suzana", "Sunčica",
    "Tada", "Tamara", "Tankosava", "Tanja", "Tatjana", "Teodora", "Tijana", "Tina", "Todora", "Tomanija", "Tomka", "Trajanka",
    "Ćana", "Ćanka", "Ćirka", "Ćuba",
    "Ubavka", "Una",
    "Fanija", "Fema", "Filipa", "Filipinka",
    "Helena", "Hranislava", "Hranislavka", "Hristina",
    "Caja", "Cajka", "Caka", "Cana", "Cveta", "Cvetana", "Cvetanka", "Ceca",
    "Časlavka", "Čedomirka",
    "Šana"
  ];
  
